name: Docker image

on:
  pull_request: {}
  push:
    branches:
      - master
      - 'support/*'
  release:
    types:
      - published

jobs:
  docker:
    runs-on: ubuntu-latest

    concurrency:
      # This makes it unique per workflow run for either PRs (head_ref) or master/tag (run_id)
      group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
      cancel-in-progress: true

    steps:
      - name: Docker image
        uses: Icinga/docker-icinga2@master
        env:
          INPUT_TOKEN: '${{ github.token }}'
          DOCKER_HUB_PASSWORD: '${{ secrets.DOCKER_HUB_PERSONAL_TOKEN }}'
